### ISSUE TITLE
Automate installation of cron

### ISSUE THREAD

**Issue by syamantm** [Netflix/chaosmonkey#13]
With database migration automated, the last remaining bit is the manual setup of the chaosmonkey cron. If that can be automated, it will pave the way to docker/rpm/deb or other types of packaging/distributions.

h3. Proposal

* add new config params(say `install.cron_expression`) to read the chaosmonkey cron, default to 1 hour before `start_hour` on week days(1-5).
* add a new command `chaosmonkey install` which will 
  * generate the bash scripts(schedule and terminate) and crontab based on this new param.
  * run database migration.
  * should be idempotent, i.e. running install multiple times should not result in inconsistencies in the system or failure. In other words, it should do a clean install on every invocation.

**Comment by lorin** [comment]
This sounds good to me. I would suggest a default of at least 2 hours before `start_hour`. The reason is related to the time zone change to/from daylight savings time.

Once the initial chaos monkey cron is set up, it doesn't change. This means that when the time zone changes, the time that this cron runs changes from the perspective of the user. On the other hand, the termination cron jobs that chaos monkey generates are always relative to the user time zone.

The upside is that you should leave at least an additional hour as a buffer in case the time zone change causes chaos monkey to generate its schedule an hour earlier than what the user was expecting when they installed it.

**Comment by syamantm** [comment]
makes sense, opened https://github.com/Netflix/chaosmonkey/pull/14
